### ISSUE TITLE
Why this if we already have Cycle.js?

### ISSUE THREAD

**Issue by HighOnDrive** [BrewhouseTeam/yolk#4]
Hi, just stumbled on your site and it leave's me wondering why Yolk is even needed or desired, when we already have the fantastic Cycle.js framework? If your not aware then please do read http://cycle.js.org/

**Comment by garbles** [comment]
Yea I've had a look at Cycle before. Why would you make such a comparison? Because they both use RxJS? Other than that, I would say that they aren't much the same at all.

**Comment by jadbox** [comment]
@garbles Forgive me for poking at this, but can you give the elevator pitch what the benefits of Yolk? From my standpoint, I think Yolk goes for a more minimal design with more reliance on Rx doing the work...

**Comment by garbles** [comment]
You're right. This is a pretty minimal library on top of Rx and virtual-dom. Both of those libraries do a lot of heavy lifting. But that is the primary benefit of Yolk - minimalist and simple. The API surface area is very small. My primary concerns for this library going forward are performance and extensibility for third parties, not adding more features. It does one thing and it does it very well.

You're going to be productive with Yolk very quickly, especially if you already know Rx. One of the great things about React is the amount of time required to onboard someone - it's fast. I enjoy being able to write components which are just functions that return JSX. Rx Observables being treated like plain values is the key benefit of Yolk and adds a lot to it's simplicity.

Contrast that with Cycle.js which has (in my opinion) a very intimidating API, even for someone who already knows Rx. I can understand where Andre is going with his design decisions, but it's just not for me.

**Comment by garbles** [comment]
Would love to hear @staltz opinion on this.

TBH I haven't used Cycle much so I can't really speak to its awesomeness. And given [this tweet](https://twitter.com/andrestaltz/status/653960734112673794), I'd say that he's not too fond of JSX. :grin:

**Comment by Frikki** [comment]
@garbles
> And given this tweet, I'd say that he's not too fond of JSX.

And you’ll find the arguments presented here https://github.com/jsforum/jsforum/issues/1

> Contrast that with Cycle.js which has (in my opinion) a very intimidating API

A very intimidating API... seriously? The API of Cycle.js is **one** function: `run(main, drivers)`. How’s that "a very intimidating API"?

**Comment by garbles** [comment]
@Frikki Relax. If I have to read over some example code several times to understand it, so I'd say it's not unreasonable to feel intimidated. It's fine if you disagree.

**Comment by Frikki** [comment]
@garbles I didn’t mean to come off as not relaxed, but I feel that "very intimidating" is rather a strong term to use for something you just didn’t immediately understand. But never mind that. What is important is the benefits understanding the concept and how to apply it.

It’s like Rx; when you first see that, it is also foreign land and takes some time to feel comfortable in.

**Comment by garbles** [comment]
@Frikki I was afraid that I would come off as if I was bashing Cycle. This was not my intent. And perhaps "very intimidating" is a strong way to put it.

Anyway, I was only trying to offer the Yolk "elevator pitch" for @jadbox. Cycle was only mentioned because the original commenter wanted me to make the comparison.

Would love to hear the Cycle elevator pitch from you over a hangout if you have time this weekend. :coffee:

**Comment by staltz** [comment]
I have to say first time I saw Yolk, it really impressed me! I really like the minimalism, the implementation (it's very neat), and some good ideas such as `onMount` events. I've seen quite a few RxJS+virtual-dom libraries and frameworks out there and Yolk definitely stands out.

I don't think there is anything "wrong". Of course there are different design decisions when compared to Cycle, but definitely each tool has its own right to exist. The elevator pitch for Yolk is clear.

The elevator pitch for Cycle.js is data flow. By being strict about I/O from/to the world in the form of driver sources and sinks (meaning no `subscribe` to be seen in user land code), we get really good data flow properties: there is a 1:1 map between application code and a data flow graph, and no need to do invasive mocking (e.g. of user events) when testing because everything is a function and side effects are only behind drivers.

**Comment by garbles** [comment]
@staltz awesome. thanks for chiming in.

**Comment by chicoxyzzy** [comment]
@garbles @staltz
crazy idea: what you guys think about making cycle.js work on top of yolk?

**Comment by garbles** [comment]
@chicoxyzzy haha pretty sure it's just a matter of writing a cycle driver if I'm not mistaken.

**Comment by staltz** [comment]
I'd rather not https://github.com/jsforum/jsforum/issues/6
